# Generated by Django

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),  # your last migration
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, null=True, blank=True),
        ),
    ]
